spring:
  profiles:
    active: dev
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
server:
  tomcat:
    uri-encoding: UTF-8
---
# 开发环境
server:
  port: 7777
spring:
  profiles: dev
  jpa:
    database: MYSQL
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://192.168.2.150:3306/hfq-dev?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username : root
    password : 123456
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: utf-8
third-party:
  weixin:
    app-id: wx5b3a1fb38f8b65b0
    appsecret: 6b7385ba7be92ad5e0d486ad28bd13f6
    token: TIESUIYA