# 开发环境
server:
  port: 8080

wechat:
  mp:
    appId: wx5b3a1fb38f8b65b0
    appSecret: 6b7385ba7be92ad5e0d486ad28bd13f6
    token: HFQWEIXINTEST

spring:
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1

logging:
  level:
    com.minghang: DEBUG
  file: D:\ProjectsLog\wx-mp-demo-dev.log