spring:
  profiles:
    active: dev

wechat:
  mp:
    url:
      # 获取access_token
      accessToken: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
    message:
      welcome: 嘿嘿嘿，你来啦！
      prompt: 嘘~别瞎说。